#! /bin/bash
claro
Menu() {
 claro
    eco -e  '\n' 
   eco "     ==================================="
    eco  " FORÇAR CONEXÃO (RAIZ) " 
   eco "        ==================================="
    eco  " ESCOLHA UM APP" 
    eco
   eco "        ==================================="
    eco  " [ 0 ] - Permições VPN" 
    eco  " [ 1 ] - CMSP" 
    echo  " [ 2 ] - CMSP KIDS" 
    eco  " [ 3 ] - Aulas Paraná" 
    eco  " [ 4 ] - Conecta Ai"   
    echo  " [ 5 ] - Applique-se" 
    eco  " [ 6 ] - Rio Educa Em Casa"   
    eco  " [ 7 ] - Loop De Conexão" 
    echo  " [ 8 ] - Alterar DNS" 
   eco "         ==================================="
   eco
    eco  "@alpacinoo007" 
    eco  "@luanw04" 
    eco
    eco  "Noob Sofre" 
    ler Aplicação
    caso $App em  
 1) App="tv.ip.edusp"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.edusp/tv.ip.my.activities.VideoActivity2 "  ; nome="CentroDeMidiasSP"  ; A2="su -c am start -n tv.ip.edusp/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.edusp/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.edusp"  ; eb="su -c pm habilitar tv.ip.edusp" ;;
 2) App="tv.ip.cmspi"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.MyVideoActivity"  ; nome="RioEducaEmCasa";   A2="su -c am start -n tv.ip.cmspi/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.SplashScreen "  ; db="su -c pm desativar tv.ip.cmspi"  ; eb="su -c pm habilitar tv.ip.cmspi" ;;
 3) App="tv.ip.aulapr"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.VideoActivity2 "  ; nome="AulaParana";   A2="su -c am start -n tv.ip.aulapr/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.aulapr"  ; eb="su -c pm habilitar tv.ip.aulapr" ;;
 4) App="tv.ip.conectaai"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.MyVideoActivity"  ; nome="Applique-se"  ; A2="su -c am start -n tv.ip.conectaai/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.conectaai"  ; eb="su -c pm habilitar tv.ip.conectaai" ;; 
 5) App="tv.ip.appliquese"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.VideoActivity2"  ; nome="Applique-se"  ; A2="su -c am start -n tv.ip.appliquese/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.appliquese"  ; eb="su -c pm habilitar tv.ip.appliquese" ;; 
 6) App="tv.ip.rioeduca"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.VideoActivity2"  ; nome="RioEducaEmCasa";   A2="su -c am start -n tv.ip.rioeduca/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.rioeduca"  ; eb="su -c pm habilitar tv.ip.rioeduca" ;;
    7) App7;;
    8) App8;;
    0) App0;;
    *)  CalmaBarboleta;   eco;  Menu;;
    esac
 ligar
    }

App0(){
claro
verificar1() {
 pervpn=$(teste-f  "$HOME/PerVPN"  &e echo 1) 
    caso $pervpn em
    1) bash PerVPN;;
    *) clear && echo  "NECESSARIO TER INTERNET NA 1° ";   eco  "VEZ PARA BAIXAR O RECURSO"  ; sono 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/PerVPN && chmod +x PerVPN && cp PerVPN $PREFIX/bin/ && ./PerVPN ; check1;;
    esac
}
verificar1
}

App7(){
claro
verificar4() {
 vpnloop=$(teste-f  "$HOME/vpn04"  &e echo 1) 
    caso $vpnloop em
    1) bash vpn04;;
    *) clear && echo  "NECESSARIO TER INTERNET NA 1° ";   eco  "VEZ PARA BAIXAR O RECURSO"  ; sono 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/vpn04 && chmod +x vpn04 && cp vpn04 $PREFIX/bin/ && ./vpn04 ; check4;;
    esac
}
verificar4
}
App8(){
claro
verificar1() {
 pervpn=$(teste-f  "$HOME/changedns2"  &e echo 1) 
    caso $pervpn em
    1) bash changedns2;;
    *) clear && echo  "NECESSARIO TER INTERNET NA 1° ";   eco  "VEZ PARA BAIXAR O RECURSO"  ; sono 4 && curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/changedns2 && chmod +x changedns2 && cp changedns2 $PREFIX/bin/ && ./changedns2 ; check1;;
    esac
}
verificar1
}

ligar () {
claro
su -c am broadcast -p com.applisto.appcloner -a com.applisto.appcloner.api.action.NEW_IDENTITY --es package_name $App [-ez clear_cache {true}] [-ez delete_app_data {true}] && sleep 12 && clear && su -c pm clear $App && su -c am start -n $App/tv.ip.my.activities.PermissionActivity && sleep 1 && su -c am startservice -n $App/tv.ip.my.controller.MyMainService && $A 3
verificar2() {
 vpn=$(ifconfig | grep -c tun0) 
    caso $vpn em
 0) sono 2; check2;;
    1) su -c am stopservice -n $App/tv.ip.my.controller.MyMainService && su -c killall $App
     esac
}
verificar2
su -c killall com.termux
}
claro
Menu
